<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Santiago Rodríguez Basabe">

<title>Detección multianual de inundación estacional en la cuenca del río Bita usando Google Earth Engine, Sentinel-1 SAR y JRC Global Surface Water</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="proyecto_final_bita_files/libs/clipboard/clipboard.min.js"></script>
<script src="proyecto_final_bita_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="proyecto_final_bita_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="proyecto_final_bita_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="proyecto_final_bita_files/libs/quarto-html/popper.min.js"></script>
<script src="proyecto_final_bita_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="proyecto_final_bita_files/libs/quarto-html/anchor.min.js"></script>
<link href="proyecto_final_bita_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="proyecto_final_bita_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="proyecto_final_bita_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="proyecto_final_bita_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="proyecto_final_bita_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen"><span class="header-section-number">1</span> Resumen</a></li>
  <li><a href="#introducción-y-justificación" id="toc-introducción-y-justificación" class="nav-link" data-scroll-target="#introducción-y-justificación"><span class="header-section-number">2</span> Introducción y justificación</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">3</span> Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-general" id="toc-objetivo-general" class="nav-link" data-scroll-target="#objetivo-general"><span class="header-section-number">3.1</span> Objetivo general</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">3.2</span> Objetivos específicos</a></li>
  </ul></li>
  <li><a href="#área-de-estudio" id="toc-área-de-estudio" class="nav-link" data-scroll-target="#área-de-estudio"><span class="header-section-number">4</span> Área de estudio</a></li>
  <li><a href="#fuentes-de-datos" id="toc-fuentes-de-datos" class="nav-link" data-scroll-target="#fuentes-de-datos"><span class="header-section-number">5</span> Fuentes de datos</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">6</span> Metodología</a></li>
  <li><a href="#resultados-y-discusión" id="toc-resultados-y-discusión" class="nav-link" data-scroll-target="#resultados-y-discusión"><span class="header-section-number">7</span> Resultados y discusión</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">8</span> Conclusiones</a></li>
  <li><a href="#disponibilidad-de-datos-y-código" id="toc-disponibilidad-de-datos-y-código" class="nav-link" data-scroll-target="#disponibilidad-de-datos-y-código"><span class="header-section-number">9</span> Disponibilidad de datos y código</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias"><span class="header-section-number">10</span> Referencias</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="proyecto_final_bita.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detección multianual de inundación estacional en la cuenca del río Bita usando Google Earth Engine, Sentinel-1 SAR y JRC Global Surface Water</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Santiago Rodríguez Basabe </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="resumen" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Resumen</h1>
<p>Los humedales de la Orinoquía colombiana presentan una dinámica hídrica fuertemente estacional, pero su monitoreo mediante percepción remota sigue limitado por la nubosidad, la heterogeneidad de coberturas y la escasez de metodologías replicables para series multianuales. Este trabajo analiza la dinámica de inundación estacional en la cuenca del río Bita durante el periodo 2017-2021, mediante imágenes Sentinel-1 SAR, procesamiento en Google Earth Engine e integración con JRC Global Surface Water. Para ello, se construyeron composiciones estacionales de retrodispersión en VV y VH, se calcularon ratios seco-húmedo en escala lineal y se seleccionó una combinación de umbrales R_VV = 1.5 y R_VH = 1.3 mediante análisis de sensibilidad. Los productos derivados mostraron diferencias claras entre polarizaciones y operadores lógicos: OR amplió la detección al incorporar respuestas individuales, mientras que AND produjo una delimitación más conservadora. La integración con JRC Global Surface Water permitió complementar la señal estacional detectada por SAR con cuerpos de agua permanentes, que no siempre presentan contraste radiométrico entre temporadas. Los resultados evidencian una variabilidad interanual marcada, con mayor extensión de inundación en 2018 y una reducción notable en 2020. La validación del producto final alcanzó una exactitud global de 0.8867, F1-score de 0.8759 y exhaustividad de 0.9677, lo que indica baja omisión de áreas inundadas, aunque con cierta comisión asociada a respuestas SAR ambiguas.</p>
<p><strong>Palabras clave:</strong> humedales; Orinoquía; Sentinel-1 SAR; retrodispersión; detección de cambios; inundación estacional; Google Earth Engine; JRC Global Surface Water; cartografía multitemporal.</p>
</section>
<section id="introducción-y-justificación" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introducción y justificación</h1>
<p>Los humedales, como otros ecosistemas fundamentales en el planeta, ofrecen servicios de diversos tipos, desde los relacionados al aprovisionamiento de agua y comida, la regulación climática y de calidad de aire, hasta servicios culturales <span class="citation" data-cites="Robertson2025">(<a href="#ref-Robertson2025" role="doc-biblioref">Robertson et&nbsp;al., 2025</a>)</span>. Considerando estas características fue creada la Convención de Ramsar: un tratado intergubernamental que propende por la conservación y gestión sostenible de estas zonas de humedales, que, por su importancia dentro de las diferentes esferas socioambientales, merecen un cuidado especial <span class="citation" data-cites="Ramsar2016">(<a href="#ref-Ramsar2016" role="doc-biblioref">Ramsar Convention Secretariat, 2016</a>)</span>. En Colombia se han designado once áreas de humedales que cubren desde el nivel del mar hasta la alta montaña <span class="citation" data-cites="JaramilloEstupinan2017 MinambienteSF">(<a href="#ref-JaramilloEstupinan2017" role="doc-biblioref">Jaramillo &amp; Estupiñán-Suárez, 2017</a>; <a href="#ref-MinambienteSF" role="doc-biblioref">Ministerio de Ambiente y Desarrollo Sostenible, n.d.</a>)</span>. Es el caso del complejo de humedales de la cuenca del río Bita, en el departamento del Vichada, que fue incluido dentro de esta lista por el Decreto 1076 de 2015, en el que se reconoce el carácter estratégico de este ecosistema. Es así que adquirir datos vía percepción remota ha sido la herramienta más útil para llevar un seguimiento del comportamiento de las diferentes dinámicas ambientales propias de los humedales y la diversidad que en ellos alberga frente a las presiones antrópicas y las afectaciones del cambio climático <span class="citation" data-cites="Guo2017">(<a href="#ref-Guo2017" role="doc-biblioref">Guo et&nbsp;al., 2017</a>)</span>.</p>
<p>Los datos de radares de apertura sintética (SAR) han sido especialmente útiles para capturar las características de los humedales <span class="citation" data-cites="Yuan2025">(<a href="#ref-Yuan2025" role="doc-biblioref">Yuan et&nbsp;al., 2025</a>)</span>. Estos ecosistemas presentan una estructura tridimensional compleja, determinada por la presencia variable de agua superficial, vegetación sumergida, flotante y emergente, junto a gradientes de humedad que cambian estacionalmente <span class="citation" data-cites="Hubinger2026 Robertson2025">(<a href="#ref-Hubinger2026" role="doc-biblioref">Hübinger et&nbsp;al., 2026</a>; <a href="#ref-Robertson2025" role="doc-biblioref">Robertson et&nbsp;al., 2025</a>)</span>. Así, los sensores de radar de apertura sintética ofrecen ventajas para el mapeo de inundación y humedales, ya que registran la energía retrodispersada por la superficie y son sensibles a la estructura de la vegetación <span class="citation" data-cites="Adeli2020">(<a href="#ref-Adeli2020" role="doc-biblioref">Adeli et&nbsp;al., 2020</a>)</span>.</p>
<p>Estudios recientes han mostrado el potencial de Sentinel-1 SAR para caracterizar la dinámica de inundación en humedales estacionales y tropicales. Un antecedente particularmente cercano es el trabajo de <span class="citation" data-cites="JeanMilien2026">Jean Milien et&nbsp;al. (<a href="#ref-JeanMilien2026" role="doc-biblioref">2026</a>)</span> en el Pantanal brasileño, donde imágenes Sentinel-1 GRD fueron utilizadas para mapear y monitorear la inundación en un humedal tropical de sabana entre 2017 y 2020. Pese a que ambas áreas de estudio son distintas en sus características biogeofísicas, representa un trabajo paralelo que expone métodos interesantes como el método de segmentación Otsu. Por otro lado, <span class="citation" data-cites="Tsyganskaya2019a">Tsyganskaya et&nbsp;al. (<a href="#ref-Tsyganskaya2019a" role="doc-biblioref">2019a</a>)</span> muestran que el agua abierta y la vegetación inundada pueden producir respuestas de retrodispersión opuestas, con disminuciones asociadas a superficies especulares e incrementos asociados a doble rebote en vegetación inundada. En la misma línea, <span class="citation" data-cites="McCormack2023">McCormack et&nbsp;al. (<a href="#ref-McCormack2023" role="doc-biblioref">2023</a>)</span> evidencian que las secuencias multitemporales Sentinel-1 pueden servir como aproximación a la dinámica hidrológica de humedales estacionales, mientras que <span class="citation" data-cites="Tupas2023b">Tupas et&nbsp;al. (<a href="#ref-Tupas2023b" role="doc-biblioref">2023b</a>)</span> advierten que los mapas de inundación basados solo en SAR pueden ser ambiguos en zonas de baja retrodispersión, sombra radar o vegetación densa.</p>
<p>A nivel nacional se posee un trabajo sobresaliente sobre la clasificación y ubicación de humedales, gestionada por el Instituto Alexander von Humboldt <span class="citation" data-cites="JaramilloVilla2015">(<a href="#ref-JaramilloVilla2015" role="doc-biblioref">Jaramillo Villa et&nbsp;al., 2015</a>)</span>, que, por más de diez años, estableció la información estándar de las cartografías oficiales de humedales y los lineamientos para clasificar la gran variedad de humedales que el país posee. Dicho trabajo incorpora diversas investigaciones que representan un robusto cuerpo del arte para la segunda mitad de la década pasada <span class="citation" data-cites="Florez2016 Quinones2016 Ricaurte2019 TrujilloLasso2017">(<a href="#ref-Florez2016" role="doc-biblioref">Flórez et&nbsp;al., 2016</a>; <a href="#ref-Quinones2016" role="doc-biblioref">Quiñones et&nbsp;al., 2016</a>; <a href="#ref-Ricaurte2019" role="doc-biblioref">Ricaurte et&nbsp;al., 2019</a>; <a href="#ref-TrujilloLasso2017" role="doc-biblioref">Trujillo &amp; Lasso, 2017</a>)</span>. Sin embargo, posterior a dicha investigación, los estudios que abordaron específicamente la Orinoquía no son caracterizados por metodologías de fotointerpretación y digitalización manual debido a su diversidad biogeofísica <span class="citation" data-cites="TrujilloLasso2017">(<a href="#ref-TrujilloLasso2017" role="doc-biblioref">Trujillo &amp; Lasso, 2017</a>)</span>. En medio de este panorama, vale la pena mencionar una reciente investigación realizada por <span class="citation" data-cites="Nino2026">Niño et&nbsp;al. (<a href="#ref-Nino2026" role="doc-biblioref">2026</a>)</span>, quienes utilizan percepción remota para el mapeo de pasturas en la Orinoquía. Es así que se reconoce la necesidad de nuevas propuestas que conduzcan hacia facilidades metodológicas para la replicabilidad y la accesibilidad del levantamiento y análisis de datos.</p>
<p>Desde una perspectiva geomática, este problema implica representar y analizar un fenómeno natural mediante datos espaciales, procesamiento satelital, integración de fuentes raster, análisis multitemporal, generación cartográfica y validación temática. Así pues, en el presente informe se plantea explorar el procesamiento de datos SAR, debido a que su capacidad de penetrar nubes e interactuar con la vegetación y superficies de agua abierta los hacen deseables para el mapeo de inundaciones asociadas a ecosistemas de humedal <span class="citation" data-cites="Adeli2020">(<a href="#ref-Adeli2020" role="doc-biblioref">Adeli et&nbsp;al., 2020</a>)</span>. De manera que la pregunta que se abordará es: ¿cómo pueden los cambios estacionales de retrodispersión Sentinel-1 SAR contribuir al mapeo de la dinámica de inundación estacional en la cuenca del río Bita?</p>
</section>
<section id="objetivos" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Objetivos</h1>
<section id="objetivo-general" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="objetivo-general"><span class="header-section-number">3.1</span> Objetivo general</h2>
<p>Analizar la dinámica multianual de inundación estacional en la cuenca del río Bita durante el periodo 2017-2021 mediante el procesamiento de imágenes Sentinel-1 SAR, la integración de JRC Global Surface Water y el uso de herramientas de análisis espacial en Google Earth Engine.</p>
</section>
<section id="objetivos-específicos" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">3.2</span> Objetivos específicos</h2>
<ol type="1">
<li><p>Construir composiciones estacionales de retrodispersión Sentinel-1 SAR para representar condiciones secas y húmedas en la cuenca del río Bita durante el periodo 2017-2021.</p></li>
<li><p>Calcular métricas de cambio seco-húmedo en las polarizaciones VV y VH, evaluar combinaciones de umbrales y comparar operadores lógicos para la detección de inundación estacional.</p></li>
<li><p>Integrar el producto estacional derivado de Sentinel-1 SAR con información de agua permanente de JRC Global Surface Water para generar cartografía anual y multianual de la dinámica hídrica.</p></li>
<li><p>Evaluar el desempeño temático del producto final mediante puntos de control y métricas de exactitud, precisión, exhaustividad y F1-score.</p></li>
</ol>
</section>
</section>
<section id="área-de-estudio" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Área de estudio</h1>
<p>La cuenca del río Bita se ubica en el departamento del Vichada, dentro de la región hidrográfica de la Orinoquía colombiana, que cuenta 14.725.346 ha de humedal, convirtiéndola en la región con más humedales en el país. De esta área, 812.312 ha pertenecen a la cuenca objeto de la presente investigación <span class="citation" data-cites="JaramilloVilla2015">(<a href="#ref-JaramilloVilla2015" role="doc-biblioref">Jaramillo Villa et&nbsp;al., 2015</a>)</span>. De tal forma, la zona hidrográfica del río contiene casi un 25% del total de la variedad de humedales en la Orinoquía <span class="citation" data-cites="Lasso2014">(<a href="#ref-Lasso2014" role="doc-biblioref">Lasso et&nbsp;al., 2014</a>)</span>, lo cual permite entender por qué pertenece a la categoría de protección y conservación Ramsar. Siendo aportante directo del Orinoco, su dinámica obedece a los regímenes estacionales característicos de esta zona del país <span class="citation" data-cites="TrujilloLasso2017">(<a href="#ref-TrujilloLasso2017" role="doc-biblioref">Trujillo &amp; Lasso, 2017</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-localizacion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-localizacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_01_localizacion_bita.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-localizacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Localización del área de estudio. Cuenca del río Bita, Orinoquía colombiana.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fuentes-de-datos" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Fuentes de datos</h1>
<p>Este estudio utilizó imágenes Sentinel-1 SAR Ground Range Detected (GRD) para analizar la dinámica hídrica multianual en la cuenca del río Bita durante el periodo 2017-2021. Se emplearon escenas en banda C, modo Interferometric Wide Swath (IW), con polarizaciones VV y VH, procesadas en Google Earth Engine. La selección de imágenes se restringió a una misma geometría orbital para reducir diferencias radiométricas asociadas al ángulo de observación y permitir comparaciones temporales consistentes entre temporadas. Esta decisión sigue criterios habituales en enfoques de detección de cambios SAR, donde las imágenes comparadas deben provenir del mismo sensor, órbita, polarización y cobertura espacial <span class="citation" data-cites="Li2018">(<a href="#ref-Li2018" role="doc-biblioref">Li et&nbsp;al., 2018</a>)</span>. La colección Sentinel-1 GRD disponible en Google Earth Engine corresponde a un producto calibrado y ortocorregido generado a partir de Sentinel-1 Toolbox, disponible en escala logarítmica asociada al coeficiente de retrodispersión <span class="citation" data-cites="GoogleEarthEngine2026 Mullissa2021">(<a href="#ref-GoogleEarthEngine2026" role="doc-biblioref">Google Earth Engine, 2026</a>; <a href="#ref-Mullissa2021" role="doc-biblioref">Mullissa et&nbsp;al., 2021</a>)</span>.</p>
<p>Para cada año se construyeron composiciones representativas de temporada seca y temporada húmeda. A partir de las composiciones se derivaron métricas de cambio en VV y VH, incluidas diferencias de retrodispersión y ratios seco-húmedo <span class="citation" data-cites="AlMehedi2025 Tsyganskaya2019b">(<a href="#ref-AlMehedi2025" role="doc-biblioref">Al Mehedi et&nbsp;al., 2025</a>; <a href="#ref-Tsyganskaya2019b" role="doc-biblioref">Tsyganskaya et&nbsp;al., 2019b</a>)</span>. La literatura previa sobre Sentinel-1 en áreas inundadas vegetadas muestra que las series temporales y las combinaciones entre polarizaciones permiten distinguir respuestas asociadas con agua abierta temporal, vegetación inundada y superficies no inundadas, aunque es recomendable acompañarlas de información auxiliar para mejorar dicha clasificación <span class="citation" data-cites="Bangira2021 Tupas2023b">(<a href="#ref-Bangira2021" role="doc-biblioref">Bangira et&nbsp;al., 2021</a>; <a href="#ref-Tupas2023b" role="doc-biblioref">Tupas et&nbsp;al., 2023b</a>)</span>.</p>
<p>Como fuente complementaria se utilizó JRC Global Surface Water para incorporar información histórica de agua superficial permanente o recurrente <span class="citation" data-cites="Pekel2016">(<a href="#ref-Pekel2016" role="doc-biblioref">Pekel et&nbsp;al., 2016</a>)</span>. Esta capa permitió diferenciar áreas con presencia de agua persistente de aquellas que presentan cambios estacionales de retrodispersión. El uso de información auxiliar de agua permanente también se encuentra en flujos recientes de mapeo de inundación con Sentinel-1 en Google Earth Engine, donde se emplea para excluir o controlar cuerpos de agua permanentes antes de interpretar cambios asociados a eventos o periodos de inundación <span class="citation" data-cites="AlMehedi2025">(<a href="#ref-AlMehedi2025" role="doc-biblioref">Al Mehedi et&nbsp;al., 2025</a>)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'knitr' was built under R version 4.5.3</code></pre>
</div>
<div id="tbl-fuentes-datos" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fuentes-datos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Fuentes de datos utilizadas para la detección multianual de inundación estacional en la cuenca del río Bita.
</figcaption>
<div aria-describedby="tbl-fuentes-datos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fuente</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Resolucion_Escala</th>
<th style="text-align: left;">Periodo</th>
<th style="text-align: left;">Uso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sentinel-1 SAR GRD</td>
<td style="text-align: left;">Raster SAR</td>
<td style="text-align: left;">10 m</td>
<td style="text-align: left;">2017-2021</td>
<td style="text-align: left;">Construcción de composiciones estacionales, cálculo de ratios y detección de cambio</td>
</tr>
<tr class="even">
<td style="text-align: left;">JRC Global Surface Water</td>
<td style="text-align: left;">Raster de agua superficial</td>
<td style="text-align: left;">30 m</td>
<td style="text-align: left;">Serie histórica / producto anual</td>
<td style="text-align: left;">Representación del componente de agua permanente o recurrente</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Límite de la cuenca del río Bita</td>
<td style="text-align: left;">Vector poligonal</td>
<td style="text-align: left;">Escala de cuenca</td>
<td style="text-align: left;">Estático</td>
<td style="text-align: left;">Delimitación del área de estudio, recorte de imágenes y cálculo de áreas</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puntos de validación</td>
<td style="text-align: left;">Vector puntual</td>
<td style="text-align: left;">300 puntos</td>
<td style="text-align: left;">2018, 2020 y 2021</td>
<td style="text-align: left;">Evaluación temática del producto final</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Google Earth Engine</td>
<td style="text-align: left;">Plataforma de procesamiento geoespacial</td>
<td style="text-align: left;">No aplica</td>
<td style="text-align: left;">Procesamiento en la nube</td>
<td style="text-align: left;">Filtrado, composición, clasificación, integración de capas, exportación y cálculo de estadísticas</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-sentinel" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sentinel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;2: Características técnicas de las imágenes Sentinel-1 GRD utilizadas para la cartografía de aguas superficiales.
</figcaption>
<div aria-describedby="tbl-sentinel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Caracteristica</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sensor</td>
<td style="text-align: left;">Sentinel-1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Producto</td>
<td style="text-align: left;">Ground Range Detected (GRD)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Banda</td>
<td style="text-align: left;">C</td>
</tr>
<tr class="even">
<td style="text-align: left;">Modo de adquisición</td>
<td style="text-align: left;">Interferometric Wide Swath (IW)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sentido de órbita</td>
<td style="text-align: left;">Ascendente</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frecuencia central</td>
<td style="text-align: left;">5.405 GHz</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longitud de onda</td>
<td style="text-align: left;">5.6 cm</td>
</tr>
<tr class="even">
<td style="text-align: left;">Resolución espacial</td>
<td style="text-align: left;">10 m</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anchura de barrido</td>
<td style="text-align: left;">250 km</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polarizaciones</td>
<td style="text-align: left;">VV y VH</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="metodología" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Metodología</h1>
<p>El procesamiento se desarrolló en Google Earth Engine a partir de imágenes Sentinel-1 SAR Ground Range Detected (GRD) para el periodo 2017-2021. Se emplearon escenas en banda C, modo Interferometric Wide Swath (IW), con polarizaciones VV y VH. Antes de construir los productos de cambio, se evaluó la disponibilidad anual de imágenes por temporada y por geometría orbital, diferenciando adquisiciones ascendentes y descendentes. Esta revisión permitió seleccionar una geometría de observación consistente para el análisis multianual, redujo diferencias radiométricas asociadas al ángulo de adquisición y evitó mezclar trayectorias orbitales en las comparaciones seco-húmedo. Esta decisión sigue criterios habituales de detección de cambios SAR, donde las imágenes comparadas deben provenir del mismo sensor, órbita, polarización y cobertura espacial <span class="citation" data-cites="Li2018">(<a href="#ref-Li2018" role="doc-biblioref">Li et&nbsp;al., 2018</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-disponibilidad-s1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disponibilidad-s1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_02_disponibilidad_sentinel1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disponibilidad-s1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Distribución anual de escenas Sentinel-1 disponibles para la cuenca del río Bita durante las temporadas seca y húmeda, separadas por órbita ascendente y descendente.
</figcaption>
</figure>
</div>
</div>
</div>
<p>El primer momento del procedimiento consistió en construir composiciones estacionales de retrodispersión para cada año del periodo de análisis. Para ello, la colección Sentinel-1 fue filtrada según el área de estudio, el rango temporal, la órbita seleccionada, el modo IW y las polarizaciones VV y VH. Posteriormente, las imágenes disponibles se agruparon en dos ventanas estacionales: temporada seca y temporada húmeda (enero a marzo y julio a septiembre, respectivamente). Para cada año y cada temporada se generaron composiciones separadas de VV y VH mediante mediana, con el fin de representar condiciones hidrológicas contrastantes y reducir la dependencia de imágenes individuales afectadas por speckle, variabilidad puntual o condiciones locales de adquisición <span class="citation" data-cites="Tsyganskaya2019b">(<a href="#ref-Tsyganskaya2019b" role="doc-biblioref">Tsyganskaya et&nbsp;al., 2019b</a>)</span>.</p>
<p>La comparación entre temporada seca y húmeda fue planteada como una adaptación estacional de los métodos de detección de cambios SAR. En la literatura, estos métodos comparan una imagen de referencia no inundada con una imagen objetivo afectada por inundación mediante operadores como diferencias, ratios o ratios logarítmicos. <span class="citation" data-cites="Li2018">Li et&nbsp;al. (<a href="#ref-Li2018" role="doc-biblioref">2018</a>)</span> señalan que el operador ratio o log-ratio es utilizado con frecuencia como indicador de cambio en imágenes SAR, debido a la naturaleza multiplicativa del speckle y a la utilidad de comparar condiciones radiométricas contrastantes. En el presente trabajo, la composición seca cumplió el papel de condición de referencia y la composición húmeda representó la condición de respuesta hidrológica estacional.</p>
<p>Para este fin, los valores de retrodispersión expresados en decibelios fueron transformados a escala lineal mediante:</p>
<p><span class="math display">\[
\sigma^0_{\text{lineal}} = 10^{\frac{\sigma^0_{\text{dB}}}{10}}
\]</span></p>
<p>Esta conversión fue necesaria porque el dB corresponde a una transformación logarítmica de la potencia retrodispersada. Por tanto, dividir directamente valores en dB no produce un cociente físico de retrodispersión. Es así que se calcularon ratios dry/wet para VV y VH:</p>
<p><span class="math display">\[
R_{VV} = \frac{VV_{\text{dry}}}{VV_{\text{wet}}}
\]</span></p>
<p><span class="math display">\[
R_{VH} = \frac{VH_{\text{dry}}}{VH_{\text{wet}}}
\]</span></p>
<p>Dichas ratios dry/wet fueron interpretadas como indicadores relativos de reducción de retrodispersión durante la temporada húmeda <span class="citation" data-cites="EODC2024 UNSpider2024">(<a href="#ref-EODC2024" role="doc-biblioref">Earth Observation Data Centre for Water Resources Monitoring, 2024</a>; <a href="#ref-UNSpider2024" role="doc-biblioref">United Nations Office for Outer Space Affairs, 2024</a>)</span>. Valores mayores que 1 indican que la señal fue más alta en seco que en húmedo. Cuanto mayor es la ratio, mayor es la disminución relativa de retrodispersión durante la temporada húmeda <span class="citation" data-cites="Tupas2023a">(<a href="#ref-Tupas2023a" role="doc-biblioref">Tupas et&nbsp;al., 2023a</a>)</span>. Este procedimiento es comparable con el trabajo de detección de inundación de <span class="citation" data-cites="AlMehedi2025">Al Mehedi et&nbsp;al. (<a href="#ref-AlMehedi2025" role="doc-biblioref">2025</a>)</span>, en el que calculan una imagen de división entre un periodo seco y un periodo inundado y aplican umbrales sobre el resultado para identificar áreas afectadas por inundación.</p>
<p>Una vez generadas las métricas de cambio, se evaluaron distintas combinaciones de umbrales para las ratios R_VV y R_VH. El objetivo fue observar la sensibilidad del área detectada ante umbrales más permisivos o más restrictivos. Para ello, se calcularon productos binarios de inundado/no inundado y se estimó el área media detectada para el periodo 2017-2021. Esta prueba permitió seleccionar una combinación intermedia, evitó umbrales demasiado bajos, que expanden la detección hacia áreas de menor contraste radiométrico, y umbrales demasiado altos, que restringen el producto a sectores con cambios más marcados.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sensibilidad-umbrales" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sensibilidad-umbrales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_03_sensibilidad_umbrales.png" class="img-fluid figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sensibilidad-umbrales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Sensibilidad del área estacional ante combinaciones de umbrales R_VV y R_VH. Área media detectada para distintas combinaciones de umbrales aplicadas a las ratios seco-húmedo de VV y VH. La línea punteada indica la combinación seleccionada para el producto final.
</figcaption>
</figure>
</div>
</div>
</div>
<p>De forma complementaria, se evaluó la estabilidad interanual de las combinaciones de umbrales. Para cada par R_VV/R_VH se calculó el área media detectada entre 2017 y 2021 y el rango mínimo-máximo observado entre años. Esta comparación permitió reconocer combinaciones con detecciones muy amplias, detecciones más conservadoras y diferencias en la variabilidad anual del área clasificada.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-resumen-umbrales" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resumen-umbrales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_04_resumen_umbrales.png" class="img-fluid figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resumen-umbrales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Relación de las combinaciones de umbrales R_VV/R_VH. El punto representa el área media detectada entre 2017 y 2021, mientras que la línea horizontal muestra el rango mínimo-máximo observado entre años para cada combinación de umbrales. El rectángulo encierra la combinación de umbrales de ratio elegida.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A partir de los umbrales seleccionados, R_VV = 1.5 y R_VH = 1.3, se generaron productos anuales de cambio estacional para el periodo 2017-2021. Para cada año se obtuvieron capas de ratio R_VV y R_VH, y combinaciones lógicas entre polarizaciones. La operación AND identificó los píxeles donde el criterio de cambio se cumplió simultáneamente en R_VV y R_VH, por lo que resultó en un producto más restrictivo. La operación OR identificó los píxeles donde el criterio se cumplió en al menos una de las dos ratios.</p>
<p><span class="math display">\[
AND = (R_{VV} \geq 1.5) \cap (R_{VH} \geq 1.3)
\]</span></p>
<p><span class="math display">\[
OR = (R_{VV} \geq 1.5) \cup (R_{VH} \geq 1.3)
\]</span></p>
<p>La separación entre R_VV y R_VH respondió a su sensibilidad física distinta. VV fue analizada por su relación con mecanismos de doble rebote y con cambios en la interacción entre agua y estructuras verticales, mientras que VH fue considerada por su relación con dispersión volumétrica, estructura de la vegetación y pérdida de señal en condiciones de agua abierta <span class="citation" data-cites="Tsyganskaya2019b">(<a href="#ref-Tsyganskaya2019b" role="doc-biblioref">Tsyganskaya et&nbsp;al., 2019b</a>)</span>. Estudios en planicies inundables vegetadas con Sentinel-1 han mostrado que las trayectorias temporales de VV, VH y sus relaciones pueden diferenciar agua abierta, vegetación baja inundada y vegetación emergente, aunque la respuesta depende del tipo de cobertura y de las condiciones ambientales <span class="citation" data-cites="Bangira2021">(<a href="#ref-Bangira2021" role="doc-biblioref">Bangira et&nbsp;al., 2021</a>)</span>.</p>
<p>De forma complementaria, se incorporó la capa JRC Global Surface Water para representar agua superficial permanente <span class="citation" data-cites="Pekel2016">(<a href="#ref-Pekel2016" role="doc-biblioref">Pekel et&nbsp;al., 2016</a>)</span>. Lo anterior responde a una limitación del enfoque del presente trabajo, pues los cuerpos de agua permanentes pueden no mostrar un contraste fuerte entre temporadas y, por tanto, no terminan siendo contados como inundación en productos basados exclusivamente en cambio. Flujos recientes de mapeo de inundación con Sentinel-1 en Google Earth Engine también emplean información de agua permanente para controlar o excluir cuerpos de agua antes de interpretar cambios asociados a inundación <span class="citation" data-cites="AlMehedi2025">(<a href="#ref-AlMehedi2025" role="doc-biblioref">Al Mehedi et&nbsp;al., 2025</a>)</span>.</p>
<p>Finalmente, los productos anuales fueron sintetizados en una capa multianual para analizar la recurrencia espacial de la respuesta hídrica entre 2017 y 2021. Para cada métrica y combinación se calculó la frecuencia de detección a lo largo del periodo, expresada como el número de años en que un píxel fue identificado como compatible con inundación estacional o cambio hídrico. También se estimó el área detectada en kilómetros cuadrados por año, producto y polarización, con el fin de comparar la magnitud espacial de la respuesta entre las diferentes formulaciones.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-flujo-metodologico" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-flujo-metodologico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_05_flujo_metodologico.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-flujo-metodologico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Flujo metodológico seguido para la detección de agua estacional, permanente y total en la cuenca del río Bita.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="resultados-y-discusión" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Resultados y discusión</h1>
<p>Los productos derivados de las operaciones R_VV, R_VH, AND y OR mostraron diferencias notorias en la extensión detectada. La operación OR produjo las áreas más amplias, al incorporar los píxeles detectados por cualquiera de las dos ratios de polarización. En contraste, AND generó el producto más restrictivo, al conservar únicamente los píxeles donde la condición de cambio se cumplió de forma simultánea en VV y VH. Entre las polarizaciones individuales, R_VH detectó más área que R_VV durante todo el periodo, lo que indica que ambas bandas no capturaron la misma respuesta estacional de la superficie.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-comparacion-operadores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-comparacion-operadores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_06_comparacion_operadores_2021.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-comparacion-operadores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Comparativa del área de agua estacional detectada para 2021. Las secciones corresponden respectivamente a OR, R_VH, R_VV y AND.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Por su parte, la serie anual mostró una mayor extensión detectada en 2017 y 2018, seguida por una reducción marcada desde 2019. El año 2018 concentró los valores máximos en todos los productos, mientras que 2020 presentó las áreas más bajas en la mayoría de las operaciones. En 2021 se observó una recuperación parcial, especialmente en R_VV y AND, aunque sin alcanzar los valores registrados al inicio del periodo. Este comportamiento sugiere una variabilidad interanual en la respuesta seco-húmedo, más evidente en los productos inclusivos que en los restrictivos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-area-operadores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-area-operadores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_07_area_operadores_2017_2021.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-area-operadores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Área estacional detectada según operación a través del periodo 2017-2021.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Con base en las figuras anteriores, se evidencia por qué AND fue seleccionado como aproximación de la inundación estacional detectada por SAR. Esta operación conservadora redujo la inclusión de píxeles asociados con respuestas aisladas de una sola polarización y privilegió las áreas donde el cambio de retrodispersión fue consistente entre VV y VH.</p>
<p>En el proceso metodológico, le siguió la integración con JRC Global Surface Water, que permitió complementar el producto de señal de inundación detectada con radar con una base de agua permanente. En este procedimiento, el componente de radar aportó la señal de cambio estacional, mientras que JRC permitió incorporar cuerpos de agua permanentes que pueden no presentar contraste fuerte entre temporada seca y húmeda. Esta integración evitó que los cuerpos de agua permanentes quedaran subrepresentados bajo la metodología de detección por cambio de temporada.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-integracion-jrc-sar-2018" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-integracion-jrc-sar-2018-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_08a_integracion_jrc_sar_2018.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-integracion-jrc-sar-2018-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Proceso de construcción del área anual integrada entre agua permanente JRC y componente radar estacional para el año 2018. Año con máxima extensión de agua registrada.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-integracion-jrc-sar-2020" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-integracion-jrc-sar-2020-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_08b_integracion_jrc_sar_2020.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-integracion-jrc-sar-2020-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Proceso de construcción del área anual integrada entre agua permanente JRC y componente radar estacional para el año 2020. Año con mínima extensión de agua registrada.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Asimismo, la suma multianual permitió identificar áreas con recurrencia de señal compatible con inundación estacional durante el periodo 2017-2021. Las zonas detectadas en varios años representaron sectores donde el contraste seco-húmedo estuvo presente a través de las temporadas. Es pertinente precisar que esta lectura no equivale, per se, a permanencia de agua; más bien, equivale a la repetición de una respuesta en el radar asociada con cambios estacionales de retrodispersión.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mapa-multianual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mapa-multianual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_09_mapa_multianual.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mapa-multianual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;10: Mapa de inundación estacional multianual detectada con Sentinel-1 SAR y JRC Global Surface Water para el periodo 2017-2021.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A propósito, se obtuvieron las cantidades totales de agua para cada año. Dicha información se puede disgregar en permanente versus agua estacional detectada con SAR. Se obtuvo un rango estable por encima de los 40 km² a través del quinquenio trabajado. Por su parte, el agua producto de inundación o cambio estacional presentó una variabilidad interanual llamativa, con magnitudes que variaron entre los valores máximos de 2018 y los mínimos de 2020.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-area-total-jrc-and" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-area-total-jrc-and-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/figura_10_area_total_jrc_and.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-area-total-jrc-and-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11: Agua total detectada en km² para la cuenca del río Bita para los años 2017-2021. Disgregada en JRC y componente estacional de ratios operados con AND.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Sobre dicho total, se realizó una validación con 300 puntos de control distribuidos en 2018, 2020 y 2021. El desempeño global alcanzó una exactitud de 0.8867, precisión de 0.80, exhaustividad de 0.9677 y F1-score de 0.8759. El bajo número de falsos negativos, 4 casos en total, muestra que el producto omitió pocas áreas clasificadas como inundadas en la referencia. La precisión fue menor por la presencia de 30 falsos positivos, especialmente en 2020, lo que indica cierta tendencia a clasificar como inundadas algunas superficies cuya respuesta SAR correspondía a un cambio, pero no fue asociado a inundación.</p>
<div class="cell">
<div id="tbl-validacion" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-validacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3: Validación del producto final de inundación estacional.
</figcaption>
<div aria-describedby="tbl-validacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Año</th>
<th style="text-align: right;">TN</th>
<th style="text-align: right;">FP</th>
<th style="text-align: right;">FN</th>
<th style="text-align: right;">TP</th>
<th style="text-align: right;">OA</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2018</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.9000</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.9348</td>
<td style="text-align: right;">0.8958</td>
</tr>
<tr class="even">
<td style="text-align: left;">2020</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">0.8300</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">0.7952</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.9300</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.9778</td>
<td style="text-align: right;">0.9263</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">0.8867</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.9677</td>
<td style="text-align: right;">0.8759</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Por año, el mejor desempeño se obtuvo en 2021, con una exactitud de 0.93 y un F1-score de 0.9263. En 2018 se obtuvo una exactitud de 0.90 y un F1-score de 0.8958, con equilibrio entre falsos positivos y falsos negativos. En 2020 el desempeño disminuyó a una exactitud de 0.83 y un F1-score de 0.7952, debido al aumento de falsos positivos. Sin embargo, ese año presentó exhaustividad de 1.00, lo que indica que todos los puntos de referencia clasificados como inundados fueron detectados por el producto.</p>
<p>El enfoque basado en ratios de retrodispersión estacional es coherente con la naturaleza del fenómeno que se busca capturar: la dinámica hídrica. A diferencia de los métodos de umbral fijo aplicados sobre imágenes individuales, la comparación seco-húmedo aprovecha la variabilidad estacional para detectar cambios en la respuesta SAR, lo que resulta pertinente en sistemas como la cuenca del río Bita. En este sentido, la composición seca como condición de referencia y la composición húmeda como señal de respuesta replican la lógica de detección de cambios documentada por <span class="citation" data-cites="Li2018">Li et&nbsp;al. (<a href="#ref-Li2018" role="doc-biblioref">2018</a>)</span>, donde el operador ratio es preferido sobre la diferencia simple por su estabilidad frente a la naturaleza multiplicativa del speckle y su capacidad para comparar condiciones radiométricas contrastantes.</p>
<p>A propósito, las diferencias observadas entre los productos R_VV, R_VH, AND y OR son una expresión esperada de las diferencias físicas entre polarizaciones. Que R_VH haya detectado sistemáticamente más área que R_VV a lo largo del periodo 2017-2021 es coherente con el comportamiento reportado por <span class="citation" data-cites="Tsyganskaya2019a">Tsyganskaya et&nbsp;al. (<a href="#ref-Tsyganskaya2019a" role="doc-biblioref">2019a</a>)</span> para áreas vegetadas inundadas, pues VH es más sensible a la dispersión volumétrica asociada con la estructura de la vegetación y muestra mayor contraste entre condiciones secas y húmedas en coberturas bajas o herbáceas <span class="citation" data-cites="Rosyid2024">(<a href="#ref-Rosyid2024" role="doc-biblioref">Rosyid et&nbsp;al., 2024</a>)</span>. VV, por su parte, responde con mayor intensidad a mecanismos de doble rebote entre láminas de agua y estructuras verticales como tallos emergentes o troncos, por lo que su señal puede incrementar en zonas de vegetación inundada alta, lo que resulta en un contraste estacional más bajo y, por ende, menor área detectada bajo el mismo umbral de ratio <span class="citation" data-cites="Bangira2021">(<a href="#ref-Bangira2021" role="doc-biblioref">Bangira et&nbsp;al., 2021</a>)</span>. En la cuenca del Bita, dominada por coberturas de sabana, morichales y vegetación riparia <span class="citation" data-cites="TrujilloLasso2017">(<a href="#ref-TrujilloLasso2017" role="doc-biblioref">Trujillo &amp; Lasso, 2017</a>)</span>, se halla que VH captura una fracción más amplia del paisaje inundado que VV, especialmente en zonas donde la dispersión volumétrica predomina sobre el doble rebote.</p>
<p>De tal manera, la elección del operador AND como aproximación final de la inundación estacional responde a un balance entre comisión y omisión. Dicho operador ofrece una lectura más conservadora que OR, que si bien maximiza la inclusión de áreas detectadas, incorpora respuestas de polarización más ambiguas. Esta disyuntiva está reconocida en la literatura: <span class="citation" data-cites="Tupas2023a">Tupas et&nbsp;al. (<a href="#ref-Tupas2023a" role="doc-biblioref">2023a</a>)</span> señalan que los métodos más inclusivos tienden a producir mayor tasa de comisión en coberturas heterogéneas. AND reduce esa ambigüedad al exigir consistencia simultánea en ambas polarizaciones y retiene solo los píxeles donde la señal de cambio estacional es representativa independientemente del mecanismo físico dominante.</p>
<p>Cabe mencionar que la interpretación de los productos de radar requiere considerar que la inundación no genera una única firma radiométrica. En superficies de agua abierta o láminas someras relativamente lisas, la señal disminuye durante la temporada húmeda por reflexión especular <span class="citation" data-cites="Amitrano2024">(<a href="#ref-Amitrano2024" role="doc-biblioref">Amitrano et&nbsp;al., 2024</a>)</span>. En vegetación inundada, en cambio, la presencia simultánea de agua y estructuras verticales puede incrementar la retrodispersión por doble o múltiple rebote, en particular en VV <span class="citation" data-cites="Tsyganskaya2019a">(<a href="#ref-Tsyganskaya2019a" role="doc-biblioref">Tsyganskaya et&nbsp;al., 2019a</a>)</span>. Esta dualidad es una de las fuentes de falsos positivos identificados en la validación, especialmente en 2020, donde se concentraron buena parte de los casos de comisión del periodo completo. En ese año, áreas con humedad superficial elevada o vegetación con respuesta SAR anómala pudieron haber superado los umbrales de ratio sin corresponder a inundación detectable en la referencia; <span class="citation" data-cites="Tupas2023b">Tupas et&nbsp;al. (<a href="#ref-Tupas2023b" role="doc-biblioref">2023b</a>)</span> documentan este patrón sistemáticamente en terrenos de baja retrodispersión y vegetación densa.</p>
<p>La incorporación de JRC Global Surface Water respondió a una limitación física estructural del enfoque basado en cambio. Los cuerpos de agua permanentes o recurrentes, al mantener baja retrodispersión tanto en temporada seca como húmeda, no generan el contraste necesario para ser detectados mediante diferencias o ratios <span class="citation" data-cites="Pekel2016">(<a href="#ref-Pekel2016" role="doc-biblioref">Pekel et&nbsp;al., 2016</a>)</span>. Los resultados ilustran esta complementariedad: el componente JRC se mantuvo relativamente estable durante el quinquenio, mientras que el componente estacional SAR presentó una variabilidad interanual más marcada. La proporción entre ambos tipos de comportamiento hidrológico es ecológicamente coherente con la naturaleza del Bita como sistema de inundación estacional, donde el pulso anual puede movilizar superficies superiores al espejo de agua permanente, tal como describen <span class="citation" data-cites="JaramilloVilla2015">Jaramillo Villa et&nbsp;al. (<a href="#ref-JaramilloVilla2015" role="doc-biblioref">2015</a>)</span> y <span class="citation" data-cites="TrujilloLasso2017">Trujillo &amp; Lasso (<a href="#ref-TrujilloLasso2017" role="doc-biblioref">2017</a>)</span> para esta cuenca.</p>
<p>Respecto a la variabilidad interanual del componente estacional, se contempla que el máximo de 2018 y el mínimo de 2020 pueden responder a causas concurrentes de distinta naturaleza. Si el pico de inundación se desplazó fuera de la ventana julio-septiembre, el composite húmedo pudo haber subestimado las condiciones de máxima inundación, lo que genera una reducción en el contraste seco-húmedo y, por tanto, el área detectada. Las ventanas estacionales fijas, útiles para garantizar comparabilidad entre años, introducen un sesgo sistemático cuando el ciclo hidrológico se desplaza, como documentan <span class="citation" data-cites="McCormack2023">McCormack et&nbsp;al. (<a href="#ref-McCormack2023" role="doc-biblioref">2023</a>)</span> para humedales estacionales analizados con series multitemporales Sentinel-1.</p>
<p>En cuanto al desempeño de la validación, los resultados globales (OA = 0.8867, F1 = 0.8759, recall = 0.9677, precisión = 0.80) son favorables y se comparan razonablemente con trabajos análogos en humedales tropicales de sabana. <span class="citation" data-cites="JeanMilien2026">Jean Milien et&nbsp;al. (<a href="#ref-JeanMilien2026" role="doc-biblioref">2026</a>)</span>, aplicando Sentinel-1 GRD en el Pantanal, un sistema Ramsar con régimen estacional comparable al del Bita, reportan una asimetría similar entre exhaustividad y exactitud, que se inscribe en la tendencia general de los métodos de radar por cambio a maximizar la detección a costa de mayor comisión. El recall de 0.9677 indica que el producto omitió apenas 4 áreas inundadas de referencia en todo el periodo, lo que es un resultado favorable para un método cuyo objetivo es no subestimar la extensión de inundación. El valor de precisión más bajo (0.80) refleja la presencia de señales SAR ambiguas que el método no puede discriminar sin información auxiliar, una limitación estructural de la banda C documentada por <span class="citation" data-cites="Adeli2020">Adeli et&nbsp;al. (<a href="#ref-Adeli2020" role="doc-biblioref">2020</a>)</span> en su revisión sistemática de métodos SAR para monitoreo de humedales.</p>
<p>Finalmente, el método presenta limitaciones que conviene precisar. La banda C de Sentinel-1 puede ver su capacidad de penetración reducida en coberturas densas o de dosel cerrado, donde la respuesta del agua bajo la vegetación queda enmascarada <span class="citation" data-cites="Hubinger2026">(<a href="#ref-Hubinger2026" role="doc-biblioref">Hübinger et&nbsp;al., 2026</a>)</span>. En formaciones de bosque de galería y morichales del Bita, teóricamente se traduciría en la subestimación del agua bajo cobertura forestal. Los umbrales seleccionados, R_VV = 1.5 y R_VH = 1.3, son parámetros empíricos derivados del análisis de sensibilidad, cuya transferibilidad a otras cuencas o periodos requiere validación específica <span class="citation" data-cites="Tupas2023a">(<a href="#ref-Tupas2023a" role="doc-biblioref">Tupas et&nbsp;al., 2023a</a>)</span>. Dicho esto, las extensiones más naturales apuntan en tres direcciones: definir ventanas estacionales de forma dinámica a partir de datos de precipitación o niveles hidrológicos; incorporar variables topográficas como HAND o posición relativa al drenaje para restringir detecciones a zonas geomorfológicamente probables <span class="citation" data-cites="Tupas2023b">(<a href="#ref-Tupas2023b" role="doc-biblioref">Tupas et&nbsp;al., 2023b</a>)</span>; y comparar estos resultados con productos ópticos previos para evaluar con mayor detalle las ventajas y limitaciones de cada aproximación.</p>
</section>
<section id="conclusiones" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusiones</h1>
<p>El objetivo general del proyecto se cumplió, pues los cambios estacionales de retrodispersión Sentinel-1 SAR permitieron analizar la dinámica multianual de inundación estacional en la cuenca del río Bita durante el periodo 2017-2021. La comparación seco-húmedo mediante ratios de polarización, implementada en Google Earth Engine, permitió detectar superficies compatibles con inundación estacional de forma consistente a lo largo del periodo de análisis.</p>
<p>En relación con el primer objetivo específico, se construyeron composiciones estacionales de retrodispersión para VV y VH, diferenciando condiciones secas y húmedas en cada año. Esta decisión permitió representar la variabilidad temporal del fenómeno sin depender de una única imagen, y redujo parte de la variabilidad puntual asociada a condiciones específicas de adquisición.</p>
<p>Respecto al segundo objetivo, el cálculo de ratios seco-húmedo permitió evaluar la respuesta diferencial de las polarizaciones VV y VH. La combinación de umbrales R_VV = 1.5 y R_VH = 1.3, junto con la comparación entre operadores AND y OR, mostró que las decisiones lógicas modifican de manera sustancial la extensión detectada. La elección de AND como producto final resultó metodológicamente justificada, pues al exigir simultáneamente umbrales de ratio en VV y VH redujo la ambigüedad radiométrica propia de coberturas heterogéneas.</p>
<p>Frente al tercer objetivo, la integración con JRC Global Surface Water permitió complementar la fracción estacional con el componente permanente de agua superficial. Esto tuvo como resultado un producto final que captura dos dimensiones distintas de la dinámica hídrica del sistema: por un lado, las áreas con señal estacional de cambio detectada por SAR; por otro, los cuerpos de agua persistentes que pueden no generar contraste suficiente entre temporadas.</p>
<p>En cuanto al cuarto objetivo, la validación temática mostró un desempeño favorable del producto final, con una exactitud global de 0.8867, F1-score de 0.8759 y exhaustividad de 0.9677. Estos valores indican baja omisión de áreas inundadas, aunque con presencia de falsos positivos asociados a respuestas SAR ambiguas, especialmente en 2020. Esta comisión no invalida el producto, pero sí evidencia que la señal SAR puede responder a condiciones de humedad, vegetación o cambios superficiales que no siempre equivalen a inundación observable en la referencia.</p>
<p>La variabilidad interanual observada, con un máximo en 2018 y un mínimo en 2020, refleja tanto condiciones hidrológicas reales como limitaciones metodológicas asociadas a ventanas estacionales fijas que pueden no coincidir con el pico de inundación en todos los años. A pesar de estas limitaciones, el flujo desarrollado permitió representar espacialmente la dinámica de inundación estacional del Bita y generar productos cartográficos reproducibles bajo un enfoque de ciencia abierta.</p>
</section>
<section id="disponibilidad-de-datos-y-código" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Disponibilidad de datos y código</h1>
<p>Los scripts de Google Earth Engine utilizados en este estudio se encuentran disponibles públicamente en el repositorio del proyecto. El repositorio incluye el código necesario para la generación de composiciones estacionales, cálculo de ratios, evaluación de umbrales, integración con JRC Global Surface Water, mapeo multianual y exportación de estadísticas espaciales.</p>
</section>
<section id="referencias" class="level1 unnumbered" data-number="10">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">10 Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Adeli2020" class="csl-entry" role="listitem">
Adeli, S., Salehi, B., Mahdianpari, M., Quackenbush, L. J., Brisco, B., Tamiminia, H., &amp; Shaw, S. (2020). Wetland monitoring using SAR data: A meta-analysis and comprehensive review. <em>Remote Sensing</em>, <em>12</em>(14). <a href="https://doi.org/10.3390/rs12142190">https://doi.org/10.3390/rs12142190</a>
</div>
<div id="ref-AlMehedi2025" class="csl-entry" role="listitem">
Al Mehedi, M. A., Smith, V., &amp; Kremer, P. (2025). A comparative analysis of urban and peri-urban flood identification using SAR imagery. <em>PLOS Water</em>, <em>4</em>(9). <a href="https://doi.org/10.1371/journal.pwat.0000269">https://doi.org/10.1371/journal.pwat.0000269</a>
</div>
<div id="ref-Amitrano2024" class="csl-entry" role="listitem">
Amitrano, D., Di Martino, G., Di Simone, A., &amp; Imperatore, P. (2024). Flood detection with SAR: A review of techniques and datasets. <em>Remote Sensing</em>, <em>16</em>(4). <a href="https://doi.org/10.3390/rs16040656">https://doi.org/10.3390/rs16040656</a>
</div>
<div id="ref-Bangira2021" class="csl-entry" role="listitem">
Bangira, T., Iannini, L., Menenti, M., Van Niekerk, A., &amp; Vekerdy, Z. (2021). Flood extent mapping in the Caprivi Floodplain using Sentinel-1 time series. <em>IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing</em>, <em>14</em>, 5667-5683. <a href="https://doi.org/10.1109/JSTARS.2021.3083517">https://doi.org/10.1109/JSTARS.2021.3083517</a>
</div>
<div id="ref-EODC2024" class="csl-entry" role="listitem">
Earth Observation Data Centre for Water Resources Monitoring. (2024). <em>GFM Flood Mapping Algorithm (LIST)</em>. <a href="https://extwiki.eodc.eu/GFM/PDD/GFM_algorithms/LIST_algorithm">https://extwiki.eodc.eu/GFM/PDD/GFM_algorithms/LIST_algorithm</a>
</div>
<div id="ref-Florez2016" class="csl-entry" role="listitem">
Flórez, C., Estupiñán-Suárez, L. M., Rojas, S., Aponte, C., Quiñones, M., Acevedo, O., Vilardy, S. P., &amp; Jaramillo Villa, U. (2016). Identificación espacial de los sistemas de humedales continentales de Colombia. <em>Biota Colombiana</em>, <em>16</em>(3), 44-62. <a href="https://doi.org/10.21068/c2016s01a03">https://doi.org/10.21068/c2016s01a03</a>
</div>
<div id="ref-GoogleEarthEngine2026" class="csl-entry" role="listitem">
Google Earth Engine. (2026). <em>Sentinel-1 SAR GRD: C-Band Synthetic Aperture Radar Ground Range Detected, Log Scaling</em>. <a href="https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S1_GRD">https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S1_GRD</a>
</div>
<div id="ref-Guo2017" class="csl-entry" role="listitem">
Guo, M., Li, J., Sheng, C., Xu, J., &amp; Wu, L. (2017). A review of wetland remote sensing. <em>Sensors</em>, <em>17</em>(4). <a href="https://doi.org/10.3390/s17040777">https://doi.org/10.3390/s17040777</a>
</div>
<div id="ref-Hubinger2026" class="csl-entry" role="listitem">
Hübinger, C., Fluet-Chouinard, E., Escobar, D., &amp; Jaramillo, F. (2026). Exploring the potential of using L-band InSAR for mapping flooded vegetation in tropical wetlands. <em>Remote Sensing of Environment</em>, <em>332</em>, 115086. <a href="https://doi.org/10.1016/j.rse.2025.115086">https://doi.org/10.1016/j.rse.2025.115086</a>
</div>
<div id="ref-JaramilloEstupinan2017" class="csl-entry" role="listitem">
Jaramillo, Ú., &amp; Estupiñán-Suárez, L. M. (2017). <em>Humedales al rescate de la sociedad</em> (pp. 59-60). Instituto de Investigación de Recursos Biológicos Alexander von Humboldt. <a href="https://doi.org/10.21068/B001.2016.412">https://doi.org/10.21068/B001.2016.412</a>
</div>
<div id="ref-JaramilloVilla2015" class="csl-entry" role="listitem">
Jaramillo Villa, U., Cortés-Duque, J., &amp; Flórez-Ayala, C. (2015). <em>Colombia anfibia: un país de humedales</em>. Instituto de Investigación de Recursos Biológicos Alexander von Humboldt.
</div>
<div id="ref-JeanMilien2026" class="csl-entry" role="listitem">
Jean Milien, E., Girard, P., &amp; Cunha, C. N. da. (2026). <em>Hydrological dynamics of large tropical savanna wetland through Sentinel-1 SAR imagery: Pantanal Ramsar site case study</em>. <a href="https://doi.org/10.20944/preprints202602.1364.v1">https://doi.org/10.20944/preprints202602.1364.v1</a>
</div>
<div id="ref-Lasso2014" class="csl-entry" role="listitem">
Lasso, C., Marrero, C., Rodríguez Olarte, D., Ramírez-Gil, H., Ajiaco-Martínez, R., Colonnello, G., Rial, A., Gordon, E., Segnini, S., Chacón, M., Antelo, R., Trujillo, F., Caro, C., Usma Oviedo, J., León, O., Jiménez, D., Agudelo, C., Sarmiento, C., Fernandez del Valle, A., &amp; Perez, K. (2014). <em>Humedales de la Orinoquia</em> (pp. 97-280).
</div>
<div id="ref-Li2018" class="csl-entry" role="listitem">
Li, Y., Martinis, S., Plank, S., &amp; Ludwig, R. (2018). An automatic change detection approach for rapid flood mapping in Sentinel-1 SAR data. <em>International Journal of Applied Earth Observation and Geoinformation</em>, <em>73</em>, 123-135. <a href="https://doi.org/10.1016/j.jag.2018.05.023">https://doi.org/10.1016/j.jag.2018.05.023</a>
</div>
<div id="ref-McCormack2023" class="csl-entry" role="listitem">
McCormack, T., Campanyà, J., &amp; Naughton, O. (2023). Reconstructing flood level timeseries at seasonal wetlands in Ireland using Sentinel-1. <em>Remote Sensing of Environment</em>, <em>299</em>. <a href="https://doi.org/10.1016/j.rse.2023.113839">https://doi.org/10.1016/j.rse.2023.113839</a>
</div>
<div id="ref-MinambienteSF" class="csl-entry" role="listitem">
Ministerio de Ambiente y Desarrollo Sostenible. (n.d.). <em>Humedales RAMSAR</em>. <a href="https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/humedales-ramsar/#tabs-1">https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/humedales-ramsar/#tabs-1</a>
</div>
<div id="ref-Mullissa2021" class="csl-entry" role="listitem">
Mullissa, A., Vollrath, A., Odongo-Braun, C., Slagter, B., Balling, J., Gou, Y., Gorelick, N., &amp; Reiche, J. (2021). Sentinel-1 SAR backscatter analysis ready data preparation in Google Earth Engine. <em>Remote Sensing</em>, <em>13</em>(10), 1954. <a href="https://doi.org/10.3390/rs13101954">https://doi.org/10.3390/rs13101954</a>
</div>
<div id="ref-Nino2026" class="csl-entry" role="listitem">
Niño, L., Rangel, O., Giraldo-Cañas, D., Sánchez-Mata, D., &amp; Minorta-Cely, V. (2026). Characterizing and mapping the grassland vegetation of the Colombian Orinoquia. <em>Grasses</em>, <em>5</em>(1), 10. <a href="https://doi.org/10.3390/grasses5010010">https://doi.org/10.3390/grasses5010010</a>
</div>
<div id="ref-Pekel2016" class="csl-entry" role="listitem">
Pekel, J.-F., Cottam, A., Gorelick, N., &amp; Belward, A. S. (2016). High-resolution mapping of global surface water and its long-term changes. <em>Nature</em>, <em>540</em>, 418-422. <a href="https://doi.org/10.1038/nature20584">https://doi.org/10.1038/nature20584</a>
</div>
<div id="ref-Quinones2016" class="csl-entry" role="listitem">
Quiñones, M., Vissers, M., Pacheco-Pascaza, A. M., Flórez, C., Estupiñán-Suárez, L. M., Aponte, C., Jaramillo Villa, Ú., Huertas, C., &amp; Hoekman, D. (2016). Un enfoque ecosistémico para el análisis de una serie densa de tiempo de imágenes de radar Alos PALSAR, para el mapeo de zonas inundadas en el territorio continental colombiano. <em>Biota Colombiana</em>, <em>16</em>(3), 63-84. <a href="https://doi.org/10.21068/c2016s01a04">https://doi.org/10.21068/c2016s01a04</a>
</div>
<div id="ref-Ramsar2016" class="csl-entry" role="listitem">
Ramsar Convention Secretariat. (2016). <em>An introduction to the Ramsar Convention on Wetlands</em>. <a href="https://www.larissab.fr">www.larissab.fr</a>
</div>
<div id="ref-Ricaurte2019" class="csl-entry" role="listitem">
Ricaurte, L. F., Patiño, J. E., Zambrano, D. F. R., Arias-G, J. C., Acevedo, O., Aponte, C., Medina, R., González, M., Rojas, S., Flórez, C., Estupiñán-Suárez, L. M., Jaramillo, Ú., Santos, A. C., Lasso, C. A., et&nbsp;al. (2019). A classification system for Colombian wetlands: An essential step forward in open environmental policy-making. <em>Wetlands</em>, <em>39</em>(5), 971-990. <a href="https://doi.org/10.1007/s13157-019-01149-8">https://doi.org/10.1007/s13157-019-01149-8</a>
</div>
<div id="ref-Robertson2025" class="csl-entry" role="listitem">
Robertson, H., Fennessy, S., Hilton, G., Job, N., Kumar, R., Simpson, M., Aggestam, F., Aldred, M., Chacón, A., Costanza, R., Davidson, N., Field, C., Finlayson, C. M., Gandra, F., Gillis, L. G., Hernández-Blanco, M., Moritsch, M., Thornton, S., Wood, K., &amp; Hoff, V. van ’t. (2025). <em>Global Wetland Outlook 2025: Valuing, conserving, restoring and financing wetlands</em>. <a href="https://doi.org/10.69556/GWO-2025-eng">https://doi.org/10.69556/GWO-2025-eng</a>
</div>
<div id="ref-Rosyid2024" class="csl-entry" role="listitem">
Rosyid, I., Palgunadi, P., &amp; Bioresita, F. (2024). Analisis Perbandingan Polarisasi VV dan VH Citra SAR Sentinel-1 untuk Identifikasi Area Genangan Banjir. <em>SERTIT</em>, <em>19</em>(3), 485-494. <a href="https://sertit.unistra.fr/en/rms/">https://sertit.unistra.fr/en/rms/</a>
</div>
<div id="ref-TrujilloLasso2017" class="csl-entry" role="listitem">
Trujillo, F., &amp; Lasso, C. A. (2017). <em>Biodiversidad del Río Bita, Vichada, Colombia</em>. Instituto de Investigación de Recursos Biológicos Alexander von Humboldt.
</div>
<div id="ref-Tsyganskaya2019a" class="csl-entry" role="listitem">
Tsyganskaya, V., Martinis, S., &amp; Marzahn, P. (2019a). Flood monitoring in vegetated areas using multitemporal Sentinel-1 data: Impact of time series features. <em>Water</em>, <em>11</em>(9). <a href="https://doi.org/10.3390/w11091938">https://doi.org/10.3390/w11091938</a>
</div>
<div id="ref-Tsyganskaya2019b" class="csl-entry" role="listitem">
Tsyganskaya, V., Martinis, S., &amp; Marzahn, P. (2019b). Flood monitoring in vegetated areas using multitemporal Sentinel-1 data: Impact of time series features. <em>Water</em>, <em>11</em>(9). <a href="https://doi.org/10.3390/w11091938">https://doi.org/10.3390/w11091938</a>
</div>
<div id="ref-Tupas2023a" class="csl-entry" role="listitem">
Tupas, M. E., Roth, F., Bauer-Marschallinger, B., &amp; Wagner, W. (2023a). An intercomparison of Sentinel-1 based change detection algorithms for flood mapping. <em>Remote Sensing</em>, <em>15</em>(5). <a href="https://doi.org/10.3390/rs15051200">https://doi.org/10.3390/rs15051200</a>
</div>
<div id="ref-Tupas2023b" class="csl-entry" role="listitem">
Tupas, M. E., Roth, F., Bauer-Marschallinger, B., &amp; Wagner, W. (2023b). Improving Sentinel-1 flood maps using a topographic index as prior in Bayesian inference. <em>Water</em>, <em>15</em>(23). <a href="https://doi.org/10.3390/w15234034">https://doi.org/10.3390/w15234034</a>
</div>
<div id="ref-UNSpider2024" class="csl-entry" role="listitem">
United Nations Office for Outer Space Affairs. (2024). <em>Recommended practice: Flood mapping with Sentinel-1 and Sentinel-2 imagery and digital terrain models</em>. <a href="https://www.un-spider.org/advisory-support/recommended-practices/recommended-practice-flood-mapping-sentinel-1-and-sentinel-2">https://www.un-spider.org/advisory-support/recommended-practices/recommended-practice-flood-mapping-sentinel-1-and-sentinel-2</a>
</div>
<div id="ref-Yuan2025" class="csl-entry" role="listitem">
Yuan, S., Liang, X., Lin, T., Chen, S., Liu, R., Wang, J., Zhang, H., &amp; Gong, P. (2025). A comprehensive remote sensing in wetland classification and mapping: Current progress and future. <em>IEEE Geoscience and Remote Sensing Magazine</em>. <a href="https://doi.org/10.1109/MGRS.2025.3637865">https://doi.org/10.1109/MGRS.2025.3637865</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>